# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eb953679c11b77b979669f57f3a16835f2a0507da9129aa74efbeb0568bb83c301ea84f37d85abce7b346997f465296cdf3f61f3d45acff4cf446255ac73f06b

test:
  secret_key_base: 2e2dad729b0d97e84c3e447fec912016d31bc2cd21ef05c2bc310152227345bde6dc8ba707b3a09331094553b3b55b00d8db276dfbad037be8dfa1ed14f0a801

# Do not keep production secrets in the repository,
# instead read values from the environment.
staging:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
